import base64,hashlib,importlib.util,json
from pathlib import Path
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

MODULE=Path(__file__).parents[1]/"install/kernel_first_install_runner.py"
spec=importlib.util.spec_from_file_location("kernel_first_install_runner",MODULE);runner=importlib.util.module_from_spec(spec);spec.loader.exec_module(runner)
def canonical(value):return (json.dumps(value,sort_keys=True,separators=(",",":"))+"\n").encode()
def test_outpost_builds_signed_host_bound_kernel_plan_and_holds_admission(tmp_path,monkeypatch):
 source=tmp_path/"source";payload=source/"payload/serein_stage1/kernel.py";payload.parent.mkdir(parents=True);payload.write_text("x=1\n");data=payload.read_bytes();layout={"payload_roots":{"payload/serein_stage1":"/usr/lib/python3/dist-packages/serein_stage1"}};(source/"install-layout.json").write_text(json.dumps(layout));installer=source/"install/kernel_first_install.py";installer.parent.mkdir();installer.write_text("# installer\n");installer_data=installer.read_bytes()
 item=["payload/serein_stage1/kernel.py",len(data),hashlib.sha256(data).hexdigest(),"0644"];rows=[{"branch":"AUTHORITY","source":item[0],"target":"/usr/lib/python3/dist-packages/serein_stage1/kernel.py","bytes":item[1],"sha256":item[2],"mode":item[3]}];manifest={"payload":[item],"installer_files":[["install/kernel_first_install.py",len(installer_data),hashlib.sha256(installer_data).hexdigest(),"0755"]],"install_denominator_digest":"sha256:"+hashlib.sha256(canonical(rows)).hexdigest()};manifest["self_digest"]="sha256:"+hashlib.sha256(canonical(manifest)).hexdigest();(source/"release-manifest.json").write_text(json.dumps(manifest))
 request={"schema":"SereinOutpostKernelInstallRequest/v1","target_vm_id":"VM4010","repository":"Kaotikking/sfos-public","source_parent":"9"*40,"source_commit":"a"*40,"source_tree":"b"*40,"archive_sha256":"c"*64,"rollback_selector":"/var/lib/serein/rollback/kernel-first-install-20260910T120000Z-abcdef123456"};request_path=tmp_path/"request.json";request_path.write_text(json.dumps(request));host={"classification":"CURRENT_BOOT_STABLE","current_boot_id":"11111111-2222-4333-8444-555555555555","latest":{"host":{"status":"PASS"},"gpu":{"status":"PASS"},"debian":{"status":"PASS"}}};host_path=tmp_path/"host.json";host_path.write_text(json.dumps(host));request_path.chmod(0o600);host_path.chmod(0o600)
 private=Ed25519PrivateKey.generate();private_path=tmp_path/"private.pem";private_path.write_bytes(private.private_bytes(serialization.Encoding.PEM,serialization.PrivateFormat.PKCS8,serialization.NoEncryption()));private_path.chmod(0o600);public_path=tmp_path/"public.pem";public_path.write_bytes(private.public_key().public_bytes(serialization.Encoding.PEM,serialization.PublicFormat.SubjectPublicKeyInfo));monkeypatch.setattr(runner,"STATE",tmp_path/"state");monkeypatch.setattr(runner,"identity",lambda user:{"user":user,"group":user,"uid":1 if user=="serein-outpost" else 2,"gid":1 if user=="serein-outpost" else 2,"primary_gid":1 if user=="serein-outpost" else 2,"members":[]})
 source_receipt={"schema":"SereinOutpostKernelSourceReceipt/v1","repository":"Kaotikking/sfos-public","ref":"refs/heads/main","source_parent":request["source_parent"],"source_commit":request["source_commit"],"source_tree":request["source_tree"],"archive_sha256":request["archive_sha256"],"release_digest":manifest["self_digest"],"inventory_digest":"sha256:"+hashlib.sha256(canonical(runner.safe_tree(source))).hexdigest()};source_receipt["signature"]=base64.urlsafe_b64encode(private.sign(canonical(source_receipt))).decode().rstrip("=");source_receipt_path=tmp_path/"source-receipt.json";source_receipt_path.write_text(json.dumps(source_receipt));source_receipt_path.chmod(0o600)
 seen={}
 def install(root,actual_source,plan):seen.update(plan);private.public_key().verify(base64.urlsafe_b64decode(plan["signature"]+"="*(-len(plan["signature"])%4)),canonical({k:v for k,v in plan.items() if k!="signature"}));return {"status":"INSTALLED_INACTIVE","receipt":plan["rollback_selector"]+"/receipt.json"}
 monkeypatch.setattr(runner,"verify_install",lambda root,plan,receipt:"e"*64)
 witness=runner.run(tmp_path,source,request_path,host_path,private_path,public_path,source_receipt_path,installer=install,lock_path=tmp_path/"lock");assert witness["admission"]=="INDEPENDENT_AUDIT_PENDING" and witness["stage1"]=="NOT_READY" and seen["current_boot_id"]==host["current_boot_id"]
